name: PR QA

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-latest
    
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11, 16, 17, 21]

    steps:
      - uses: actions/checkout@v4
      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dmaven.javadoc.skip=true -V -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Dmaven.wagon.http.pool=false verify
      - name: Upload greenfield coverage report
        if: matrix.java-version == 8
        uses: actions/upload-artifact@v4
        with:
          name: greenfield-report
          path: greenfield-apps/target/site/jacoco/
      - name: Upload GUI coverage report
        if: matrix.java-version == 8
        uses: actions/upload-artifact@v4
        with:
          name: gui-report
          path: gui/target/site/jacoco/
      - name: Upload PDFBox coverage report
        if: matrix.java-version == 8
        uses: actions/upload-artifact@v4
        with:
          name: pdfbox-report
          path: pdfbox-apps/target/site/jacoco/

  coverage:
    name: Quality Assurance
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v4
      - name: Download greenfield coverage report
        uses: actions/download-artifact@v4
        with:
          name: greenfield-report
          path: greenfield-apps/target/site/jacoco/
      - name: Download GUI coverage report
        uses: actions/download-artifact@v4
        with:
          name: gui-report
          path: gui/target/site/jacoco/
      - name: Download PDFBox coverage report
        uses: actions/download-artifact@v4
        with:
          name: pdfbox-report
          path: pdfbox-apps/target/site/jacoco/
      - name: Codecov coverage reporting
        uses: codecov/codecov-action@v2
        with:
          files: greenfield-apps/target/site/jacoco/jacoco.xml, gui/target/site/jacoco/jacoco.xml, pdfbox-apps/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: Codacy coverage reporting
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: greenfield-apps/target/site/jacoco/jacoco.xml, gui/target/site/jacoco/jacoco.xml, pdfbox-apps/target/site/jacoco/jacoco.xml
      - name: Codacy analysis reporting
        uses: codacy/codacy-analysis-cli-action@master
