name: Trigger increment action in webapp-server

on:
  push:
    tags:
      - v*

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Create workflow dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
             owner: 'veraPDF',
             repo: 'verapdf-webapp-server',
             workflow_id: 'version-auto-increment.yml',
             ref: 'master'
            })
